### ISSUE TITLE
adding VGM support to Mixxx

### ISSUE THREAD

**Issue by ghost** [ValleyBell/libvgm#116]
Hi

I'm not a developer but I'm looking for somebody who can help or implement VGM support in the program Mixxx

https://mixxx.org/

Please read all discussion here: what i'm trying and what we discussed

https://github.com/mixxxdj/mixxx/issues/12122

Thanks in advance!!!

**Comment by ValleyBell** [comment]
I don't think it is my task to add libvgm support to other programs.  
However I will be there for response/reply if anyone needs help with it.

Also, since the user (dj-girl) deleted her account, I assume this is has resolved itself.

**Comment by vgm-girl** [comment]
Hi

I was dj-girl who requested this! I deleted my account because nobody wanted to help me. (I'm not active on github for anything else)

I'm an autistic girl and it's impossible for me to learn programming to do this myself. I have disabilities because of my autism.
It's my DREAM to have VGM in Mixxx.
Is there a way you want to try this?
You will make my dream come true...

**Comment by Eoin-ONeill-Yokai** [comment]
My advice here would be to ask someone from the FFMPEG team (open source project) if they could somehow incorporate libvgm as a build option there. 

There's actually a lot of good that could come from this (Jellyfin support, other web service support) and it might be worth venturing. It's just not the right place to ask for this -- this is strictly a library for players to implement.

**Comment by vgm-girl** [comment]
Thanks a lot for the help but the ffmpeg github does not have the 'issues' so i can't write anything there

https://github.com/FFmpeg/FFmpeg

Are you a developer who can help?

It's getting hopeless for me :'(

**Comment by Wohlstand** [comment]
> Update: I asked on the chat of ffmpeg.

Ye, FFMPEG team prefers to talk and track issues on their own places, and therefore they disabled issues at GitHub.

**Comment by vgm-girl** [comment]
Hi @Wohlstand 
Are you interested in my request for Mixxx?
