### ISSUE TITLE
Library logs to console, impossible to disable

### ISSUE THREAD

**Issue by jpcima** [ValleyBell/libvgm#21]
Hi. When the library plays in a ncurses program in the console, warning messages will be printed and disturb the display.

The situation will be improved if we can replace printf calls with a logging function which can be user-defined and redirect to another channel, like a file.

For example, this one annoys; and I'm sure to have met also a few others cases.
https://github.com/ValleyBell/libvgm/blob/8727d421f28ef185069ba6a4bfe413f0473ef79c/player/vgmplayer.cpp#L1112

**Comment by ValleyBell** [comment]
Yeah, that's a known problem. I already have it on my TODO list for things to be fixed. (by using callback functions, probably)

**Comment by ValleyBell** [comment]
I finally implemented a proper logging callback system with a7215f4921001bb7bfa6377bd2ba22331b9a269a.

As of 0f0b01a49fe0619bde0df1666dbf550d188df3aa, all components in "emu" and "player" use the new system.
(Audio drivers OSS and SADA still use printf at a few places, but I'll deal with that later.)
