### ISSUE TITLE
alignment fault on wasm

### ISSUE THREAD

**Issue by vampirefrog** [ValleyBell/libvgm#23]
Hi, there is an alignment fault when casting smaller width int pointers to bigger width ones, for example char * to uint16*. This fault is specific to web assembly, the only place this takes place in libvgm seems to be in vgmplayer.cpp:316. Here is the simple fix:

```
while(curPos < eotPos && _fileData[curPos] != 0x00 && _fileData[curPos + 1] != 0x00)
```

**Comment by ValleyBell** [comment]
This issue should be fixed by commit 70ce85042a74591479965bf5e06090f110d26f56.
