### ISSUE TITLE
add a compilation option to support only Project2612 VGMs

### ISSUE THREAD

**Issue by vampirefrog** [ValleyBell/libvgm#25]
Hello, perhaps you can add a compilation option that only enables the chips required by the VGM files on Project2612. This way the compiled code will be smaller and I can replace the JS VGM player in the Project2612 pages.

**Comment by ValleyBell** [comment]
There already is one:
https://github.com/ValleyBell/libvgm/blob/a3fb9fcd9378b1f831ad9f1f1664867f6f56b00f/emu/CMakeLists.txt#L81

**Comment by vampirefrog** [comment]
perfect, thanks!
