### ISSUE TITLE
There is no support for audio output on Mac OS X

### ISSUE THREAD

**Issue by ValleyBell** [ValleyBell/libvgm#28]
I would like to have support for a native Mac OS X audio API like Core Audio.

Unfortunately I don't have access to a Mac, so I can't do it by myself.

**Comment by kode54** [comment]
I can contribute a simple Core Audio player, based on a simple command line player I wrote for the Syntrax reverse engineering effort a friend did and I helped clean up and improve.

I also have a MBP, and a working Hackintosh setup on my main desktop, both running 10.14.5.

**Comment by ValleyBell** [comment]
Thanks, that would be great!

**Comment by ValleyBell** [comment]
Fixed by #30
