### ISSUE TITLE
How to change cores?

### ISSUE THREAD

**Issue by jprjr** [ValleyBell/libvgm#34]
Hi there, I was trying to figure out how to use the player library to change out different emulation cores for chips.

I thought it might have something to do with `SetDeviceOptions`, but I can't quite figure out how to say "for YM2612, use the NUKE core"

I tried going through the code for the example player, but I'll be honest, I got lost pretty quickly. I think I need to combine the device ID (`DEVID_YM2612`) with the instance ID (`0`) to form the `id` parameter for `SetDeviceOptions`?

I'm also not sure if setting device options should be called:

* Before Loading a file
* After a loading file, but before calling Start
* After calling Start
* Some other time?

Any help/pointers would be great, thank you so much!!

**Comment by ValleyBell** [comment]
Basically, it works like this:
```cpp
PLR_DEV_OPTS devOpts;
UINT32 deviceID = PLR_DEV_ID(DEVID_YM2612, instance);
player->GetDeviceOptions(deviceID, devOpts);
devOpts.emuCore = FCC_NUKE;
player->SetDeviceOptions(deviceID, devOpts);
```
When the high bit is not set for the deviceID, you select chips based on what is currently in use.
(Yes, this needs documentation. I'm still far from finished with the player stuff.)

You can set device options any time, but most options (like setting emulation cores) only have an effect when calling `Start()`.  
*coreOpts* might have an immediate effect. *muteOpts* always have an immediate effect.

Settings are kept as long as the player object lives.

**Comment by jprjr** [comment]
Thank you so much!!!
