### ISSUE TITLE
Device panning settings seem to differ from vgmplay

### ISSUE THREAD

**Issue by jkl1337** [ValleyBell/libvgm#49]
At the line below: https://github.com/ValleyBell/libvgm/blob/17876de62b6eae39153689545df6fcdeee9be8d3/player/vgmplayer.cpp#L1368
some default non-zero panning settings are applied to some models of devices. I may have missed it, but I can't see where similar is done in vgmplay. Curious as to the reason for the difference.

**Comment by ValleyBell** [comment]
I'm afraid that's leftover from testing per-channel panning.
I'll remove the hardcoded panning soon.

**Comment by ValleyBell** [comment]
As of aa847bc89e8afe3ba69b6e1878875f84052be9c6, panning is not hardcoded into vgmplayer.cpp anymore. (Sorry - "soon" took longer than originally expected.)

Even though panning is still applied in player.cpp, I consider the issue fixed, as it doesn't affect client applications anymore.
https://github.com/ValleyBell/libvgm/blob/e18aaf25a3d516ac802fadea2818ec4344177d7e/player.cpp#L264-L267
