### ISSUE TITLE
State of the library

### ISSUE THREAD

**Issue by emoon** [ValleyBell/libvgm#5]
Hi,

I'm currently using VGMPlay for VGM playback in my player called HippoPlayer over at https://github.com/emoon/HippoPlayer and the way the library work is less than idea and quite messy.

I'm interested in switching over to using this library instead and I'm wondering what the current state is?

**Comment by ValleyBell** [comment]
The library can't replace VGMPlay yet.

Everything related to sound emulation is complete (and audio output, but you won't need that), but VGM parsing/playing is still missing completely.  
However, VGM playback is the next thing I will work on. (I recently added S98 and DRO playback in order to do some scouting, before I begin with the actual VGM player.)

**Comment by emoon** [comment]
Awesome! I will keep track of the progress and likely switch over when possible then.

**Comment by emoon** [comment]
Hey,

Sorry for poking at this old issue, but I wonder if it would make sense to switch over to libvgm from the old vgmplay codebase now? (I really want to!) as long as it's somewhat supports most things from the old one. I read in the #20 about the general roadmap, but it's a bit hard to know what exact state the library is right.

Thanks!

**Comment by ValleyBell** [comment]
I think libvgm is pretty much ready for the switch.

- `audio` sub-library: finished, API is stable
- `emu` sub-library: I'd say 99% finished.
  There is one deprecated function in EmuStructs.h that I will remove in the future, but other than that the API should be stable.
- `player` sub-library: All important functionality is done. All features from the old VGMPlay/in_vgm are there.
  The API is unstable though and may change. But I probably won't do any larger renaming before making the "player" lib provide a pure C API.

All in all I think switching over to libvgm now should be a good idea now. I added the last really important feature with c768e53ea886a329dcea67bf989525a237f8cafe.
You can take a look at the libvgm-based VGMPlay and in_vgm for examples on how to use libvgm.

**Comment by emoon** [comment]
Awesome! Thanks for the info 🙂
