### ISSUE TITLE
Hanging up on possibly incorrect .vgm files

### ISSUE THREAD

**Issue by vitamin-caig** [ValleyBell/libvgm#51]
Hello!

I've found several modules which hang player at all:(

http://ftp.amigascne.org/mirrors/ftp.modland.com/pub/modules/Video%20Game%20Music/Sega%20Megadrive/Barry%20Leitch/Lotus%20Turbo%20Challenge/

**Comment by ValleyBell** [comment]
... oh yeah, those files have a 0-sample loop.

I'll fix this soon.

**Comment by vitamin-caig** [comment]
0-sample loop is not a problem itself - I'm just checking out 'stopped' state to restart playback.
The main issue is no 'wait' commands between loop point (data by loop offset), so interpreter just loops forever...

**Comment by ValleyBell** [comment]
A "0-sample loop" and "no 'wait' commands between loop point" is the same thing - and exactly the problem here.

The old VGMPlay filters that out (and prints a warning), but I missed that when rewriting the VGM player.

**Comment by vitamin-caig** [comment]
There're also crashes with some vgms. Should I report another issue or may point them here?

**Comment by ValleyBell** [comment]
Feel free to point them here.

**Comment by vitamin-caig** [comment]
Here the problematic tracks references - all the vgm files in packs below crash player.

https://vgmrips.net/packs/pack/pac-slot-arcade
https://vgmrips.net/packs/pack/winning-run-91-namco-system-21

**Comment by ValleyBell** [comment]
The freezing issue is fixed with 4d4a84e2662fae2a34887465f903c1acea275edc.

The crashes are fixed with bd4c7986db11c741aee3d4adcb24b4a6ebc3152b (Pac-Slot) and cc03e687294f90d869b14331fe605858ce8c30c9 (Winning Run '91).
