### ISSUE TITLE
Segfault in player/vgm2wav

### ISSUE THREAD

**Issue by jprjr** [ValleyBell/libvgm#54]
Hi there -

If I set player to show file info (or use vgm2wav, which always shows it) with this [Psycho Solider Rip](https://vgmrips.net/packs/pack/psycho-soldier-snk-triple-z80), a segfault occurs.

It looks like [`pdi.devCfg`](https://github.com/ValleyBell/libvgm/blob/e1b03bebbb7450a152d2a69599cb807d3f544772/player.cpp#L272) is a null pointer when using that particular rip.

If I checkout commit 6033792f3255dc0e2850c40a3cd0b8afd21535e2, the `Clock` displays (and I don't get a segfault), so I think it has something to do with the changes from 6fdb6304926b594abc28b923a5b6265c36a91b68 (DRO/S98/VGMPlayer: generate device config on load).

Is there behavior that needs to be changed in player and vgm2wav?

**Comment by ValleyBell** [comment]
pdi.devCfg shouldn't be NULL. I'll have a look.

**Comment by ValleyBell** [comment]
Fixed with cf1dccfd68c9bf97424aec9625c0f803e6a26770

It looks like I accidentally deleted a wrong line when I tidied up the code.
