### ISSUE TITLE
Tempo won't be changed

### ISSUE THREAD

**Issue by Wohlstand** [ValleyBell/libvgm#87]
Recently I tried to experiment with the library, and I found it has the inability to change the tempo while playing VGM files (didn't test other formats yet):

```cpp
PlayerA *player;
//...
player->SetPlaybackSpeed(tempo);
```
Attempting to set any value has no effect absolutely...

**Comment by ValleyBell** [comment]
Yes, the function is not implemented yet in any of the formats.  
Sorry, it is still on my TODO list.

**Comment by Wohlstand** [comment]
I see, thanks for the note

**Comment by kode54** [comment]
I implemented this in a PR. #92
