### ISSUE TITLE
Looping is inconsistent

### ISSUE THREAD

**Issue by polygonnedpotato** [ValleyBell/libvgm#94]
Playing vgm files leads to playback being cut off near the end and instead of looping properly, goes back to the beginning of the file.

**Comment by ValleyBell** [comment]
please post a link to an example file or attach one

**Comment by polygonnedpotato** [comment]
[Here](https://drive.google.com/file/d/1l1VFfsiDuvfJmHuKAxTemHT-18DavioW/view?usp=sharing)

**Comment by ValleyBell** [comment]
I'll just quote the VGMPlay file information:

```
File Name:      17 - Drowning.vgm
[...]
Format:         VGM 1.50    Gain: 1.00    Loop: No
```

"no loop" means it won't loop, because the file itself says it is not supposed to loop.
